stages:
  - build
  - test

linux-x64:
  image: 'camilstaps/clean:nightly'
  stage: build
  needs: []
  before_script:
    - install_clean_nightly.sh base lib-platform test
    - apt-get update -qq
    - apt-get install make
  script:
    - make -C src/linter eastwood-lint
  artifacts:
    when: always
    paths:
      - src/linter/eastwood-lint

test:
  image: 'camilstaps/clean:nightly'
  stage: test
  needs: []
  before_script:
    - install_clean_nightly.sh bundle-complete
    - apt-get update -qq
    - apt-get install make
  script:
    - make -C test runTest
  artifacts:
    when: always
    paths:
      - test/junit.xml
    reports:
      junit: test/junit.xml
